'use client';

import { ArrowRight, Bot, BrainCircuit, ChefHat, NotebookText, SplitSquareHorizontal, User } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import Link from "next/link";
import Image from "next/image";

// Re-organize the features for a better layout
const primaryFeatures = [
  {
    title: "AI-Powered Meal Plan",
    description: "Get a fully personalized weekly meal plan generated by our AI to perfectly match your goals.",
    href: "/meal-plan/optimized",
    icon: Bot,
    cta: "Generate AI Plan",
    variant: "default" as "default",
  },
  {
    title: "Current Meal Plan",
    description: "View, edit, and track your ongoing weekly meal schedule. Manually adjust or optimize with AI.",
    href: "/meal-plan/current",
    icon: NotebookText,
    cta: "View Your Plan",
    variant: "outline" as "outline",
  },
  {
    title: "Smart Calorie Planner",
    description: "Calculate and fine-tune your daily calorie and macronutrient targets for precise results.",
    href: "/tools/smart-calorie-planner",
    icon: BrainCircuit,
    cta: "Open Planner",
    variant: "outline" as "outline",
  },
  {
    title: "Your Profile",
    description: "Keep your personal information, goals, and preferences up-to-date for the best recommendations.",
    href: "/profile",
    icon: User,
    cta: "Update Profile",
    variant: "outline" as "outline",
  },
];

const toolFeatures = [
    {
        title: "Macro Splitter",
        description: "Distribute your daily macronutrients across your meals to fit your eating schedule.",
        href: "/tools/macro-splitter",
        icon: SplitSquareHorizontal,
    },
    {
        title: "Meal Suggestions",
        description: "Get quick, AI-powered meal ideas for any mealtime based on your macro needs.",
        href: "/tools/meal-suggestions",
        icon: ChefHat,
    }
]

export default function DashboardPage() {
  return (
    <div className="flex flex-col gap-8 md:gap-12">
      {/* Hero Section */}
      <Card className="w-full overflow-hidden border-2 border-primary/20 shadow-xl">
        <div className="grid md:grid-cols-2 items-center">
            <div className="p-8 lg:p-12">
                <h1 className="text-3xl md:text-4xl font-bold tracking-tight text-primary">
                Welcome Back to NutriPlan!
                </h1>
                <p className="mt-4 text-lg text-foreground/80">
                Your journey to personalized nutrition starts here. Let's achieve your goals together.
                </p>
                <div className="mt-6">
                <Link href="/meal-plan/optimized" passHref legacyBehavior>
                    <Button size="lg" className="text-lg py-7 px-8">
                        Generate Your AI Meal Plan
                        <ArrowRight className="ml-2 h-5 w-5" />
                    </Button>
                </Link>
                </div>
            </div>
            <div className="relative h-64 md:h-full min-h-[250px] md:min-h-[350px]">
                <Image
                src="https://placehold.co/600x400.png"
                alt="A vibrant plate of healthy food"
                layout="fill"
                objectFit="cover"
                data-ai-hint="healthy food plate"
                />
            </div>
        </div>
      </Card>
      {/* Primary Features Grid */}
      <div className="space-y-4">
        <h2 className="text-2xl font-semibold tracking-tight text-center">Your Nutrition Hub</h2>
        <p className="text-center text-muted-foreground">
          All the essential tools to manage your diet and progress.
        </p>
        <div className="grid grid-cols-1 gap-6 pt-4 sm:grid-cols-2 lg:grid-cols-4">
          {primaryFeatures.map((feature) => (
            <Card key={feature.title} className="flex flex-col shadow-md hover:shadow-lg transition-shadow duration-300">
              <CardHeader className="flex-grow">
                <feature.icon className="h-10 w-10 mb-3 text-accent" />
                <CardTitle>{feature.title}</CardTitle>
                <CardDescription>{feature.description}</CardDescription>
              </CardHeader>
              <CardContent>
                <Link href={feature.href} passHref legacyBehavior>
                  <Button className="w-full" variant={feature.variant}>
                    {feature.cta}
                  </Button>
                </Link>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
      {/* Additional Tools Section */}
      <div className="space-y-4">
       <h2 className="text-2xl font-semibold tracking-tight text-center">More Tools</h2>
        <p className="text-center text-muted-foreground">
         Fine-tune your plan with these specialized tools.
       </p>
       <div className="grid grid-cols-1 gap-6 pt-4 md:grid-cols-2">
           {toolFeatures.map((tool) => (
               <Card key={tool.title} className="shadow-md hover:shadow-lg transition-shadow duration-300 flex items-center p-6">
                   <div className="mr-6">
                       <tool.icon className="h-12 w-12 text-primary" />
                   </div>
                   <div className="flex-grow">
                       <CardTitle className="text-xl mb-1">{tool.title}</CardTitle>
                       <CardDescription className="mb-4">{tool.description}</CardDescription>
                        <Link href={tool.href} passHref legacyBehavior>
                           <Button variant="secondary">
                               Open Tool <ArrowRight className="ml-2 h-4 w-4" />
                           </Button>
                       </Link>
                   </div>
               </Card>
           ))}
       </div>
      </div>
    </div>
  );
}
